name: Workflow with Outputs
on: push
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Build Step
              id: step1
              run: echo "version=1.0.0" >> $GITHUB_OUTPUT
    deploy:
        runs: ubuntu-latest
        steps:
            - name: Deploy Step
            