name: Workflow Secrets
on:
  push:
    paths:
      - .github/*

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: "Build Step"
        run: echo "In Build Step"
      - name: "Access Workflow Secrets"
        run: echo "Hello, ${{ secrets.DOCKER_PASSWORD }}"
