name: Workflow S3 Static Website

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v6
        with:
          role-to-assume: arn:aws:iam::758854589827:role/gha-demo-role
          aws-region: us-east-1
          role-session-name: GitHub_to_AWS_via_FederatedOIDC

      - name: Verify AWS Credentials
        run: aws sts get-caller-identity

      - name: Sync S3 Bucket
        run: |
          aws s3 cp index.html s3://thebalabanana.store/index.html
