name: Hello World
on: workflow_dispatch
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: "Build Step"
        run: echo "In Build Step"
  test: 
      runs-on: ubuntu-latest
      steps:
        - name: "Test step 1"
          run:  echo "In test step"
  deploy:
      runs_on: ubuntu-latest
      steps:
        - name: "Deploy step 1"
          run: echo "In deploy step"
