name: Push Trigger Workflow
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: "Build Step"
        run: echo "In Build Step"
  test: 
      runs-on: ubuntu-latest
      needs: build
      steps:
        - name: "Test step 1"
          run:  echo "In test step"
  deploy:
      runs-on: ubuntu-latest
      needs: test
      steps:
        - name: "Deploy step 1"
          run: echo "In deploy step"
